// CanvasGUI.js - http://github.com/sargodarya/CanvasGUI
'use strict';var GUI=GUI||{};GUI.Manager=function(){this.domElement=document.createElement("canvas");this.domElement.id="gui";this._size=new GUI.Point(window.innerWidth,window.innerHeight);this._ctx=this.domElement.getContext("2d");this._ctx.canvas.width=this._size.x;this._ctx.canvas.height=this._size.y;this._stage=new GUI.DisplayObject;this._focus=null;this._stage._ctx=this._ctx;this._stage.tag("Stage");this._stage.size(this._size.x,this._size.y);this._mouse=new GUI.Mouse};
GUI.Manager.prototype.addChild=function(a){this._stage.addChild(a)};GUI.Manager.prototype.setSize=function(a,b){this._ctx.canvas.width=a;this._ctx.canvas.height=b;this._stage.size(this._size.x,this._size.y);this._stage.redraw();GUI.Display.dirtyRectangles.push(new GUI.Rect({width:a,height:b},{x:0,y:0}))};GUI.Manager.prototype.clean=function(){this._stage.removeAllChilds();this._stage.invalidateRect()};
GUI.Manager.prototype.injectMouseMove=function(a){50===a.which&&(a.stopImmediatePropagation(),a.preventDefault());this._mouse.injectMoveEvent(a);var a=this._mouse._cursor.rect(),b=GUI.Display.getTLPosition(this._mouse._cursor);a.position(b.x,b.y);this._stage.redrawRect(a)};GUI.Manager.prototype.injectMouseClick=function(){var a=this._mouse.position();this._focus=this._stage.getChildAtPoint(new GUI.Point(a.x,a.y))};
GUI.Manager.prototype.injectKeyDown=function(a){this._focus&&this._focus.handleKeyDown&&this._focus.handleKeyDown(a)};GUI.Manager.prototype.render=function(){if(GUI.Display.dirtyRectangles.length){for(var a=0;a<GUI.Display.dirtyRectangles.length;a++){var b=GUI.Display.dirtyRectangles[a];b._position=GUI.Display.getDenormalizedPosition(b._position.x,b._position.y);this._ctx.clearRect(b.position().x,b.position().y,b.size().width,b.size().height)}this._stage.render();GUI.Display.dirtyRectangles=[]}};
GUI.Point=function(a,b){this._position={x:a,y:b}};GUI.Point.prototype.position=function(a,b){if("number"==typeof a)this._position={x:a,y:b};return this._position};GUI.Point.prototype.toString=function(){return"[x:"+this._position.x+",y:"+this._position.y+"]"};GUI.Rect=function(a,b){this._size=a;this._position=b};GUI.Rect.prototype.size=function(a,b){if("number"==typeof a)this._size={width:a,height:b};return this._size};
GUI.Rect.prototype.position=function(a,b){if("number"==typeof a)this._position={x:a,y:b};return this._position};GUI.Rect.prototype.containsRect=function(a){for(var b=a._position.x,c=a._position.x+a._size.width,d=a._position.y,a=a._position.y+a._size.height,b=[new GUI.Point(b,d),new GUI.Point(b,a),new GUI.Point(c,d),new GUI.Point(c,a)],c=0;c<b.length;c++)if(this.containsPoint(b[c]))return!0;return!1};
GUI.Rect.prototype.containsPoint=function(a){var b=this._position.x,c=this._position.x+this._size.width,d=this._position.y,e=this._position.y+this._size.height,a=a.position();return b<=a.x&&a.x<=c&&d<=a.y&&a.y<=e?!0:!1};GUI.Rect.prototype.toString=function(){return this._size.width+"/"+this._size.height+"/"+this._position.x+"/"+this._position.y};
GUI.DisplayObject=function(){this._hasDirty=this._dirty=!1;this._parent=null;this._children=[];this._position={};this._position.x=0;this._position.y=0;this._z=1;this._anchorPoint={};this._anchorPoint.x=0;this._anchorPoint.y=0;this._visible=!0;this._size={};this._size.width=0;this._size.height=0;this._tag="";this._ctx=null};GUI.DisplayObject.prototype.position=function(a,b){this.invalidateRect();this._position.x=a;this._position.y=b;this.invalidateRect()};
GUI.DisplayObject.prototype.rect=function(){return new GUI.Rect({width:this._size.width,height:this._size.height},{x:this._position.x,y:this._position.y})};GUI.DisplayObject.prototype.z=function(a){if("Number"===typeof a)this._z=a;return this._z};GUI.DisplayObject.prototype.anchorPoint=function(a,b){return this._anchorPoint={x:a,y:b}};GUI.DisplayObject.prototype.isVisible=function(a){if("boolean"===typeof a)this._visible=a;return this._visible};
GUI.DisplayObject.prototype.size=function(a,b){if(a)this._size.width=a;if(b)this._size.height=b;return{width:this._size.width,height:this._size.height}};GUI.DisplayObject.prototype.tag=function(a){if("string"===typeof a)this._tag=a;return this._tag};GUI.DisplayObject.prototype.isDirty=function(){this._dirty=!0;null!=this._parent&&this._parent.setDirtyChilds()};GUI.DisplayObject.prototype.setDirtyChilds=function(){this._dirty=!0;null!=this._parent&&this._parent.setDirtyChilds()};
GUI.DisplayObject.prototype.redraw=function(){this._dirty=!0;for(var a=0;a<this._children.length;a++)this._children[a].redraw()};GUI.DisplayObject.prototype.redrawRect=function(a){this._dirty=!0;this._parent&&this.invalidateRect();for(var b=0;b<this._children.length;b++){var c=this._children[b].rect(),d=GUI.Display.getTLPosition(this._children[b]);c.position(Math.round(d.x),Math.round(d.y));a.containsRect(c)&&this._children[b].redrawRect(a)}};
GUI.DisplayObject.prototype.getChildAtPoint=function(a){for(var b=this,c=0;c<this._children.length;c++){var d=this._children[c].rect(),e=GUI.Display.getTLPosition(this._children[c]);d.position(e.x,e.y);if(d.containsPoint(a)){b=this._children[c].getChildAtPoint(a);break}}return b};
GUI.DisplayObject.prototype.addChild=function(a){GUI.assert(null===a._parent,"DisplayObject already has a parent");GUI.assert(a._parent!=this,"DisplayObject was already added to parent");a._parent=this;a._ctx=this._ctx;this._children.push(a);return!0};GUI.DisplayObject.prototype.removeChild=function(a){a._parent=null;this._children.remove(a)};GUI.DisplayObject.prototype.removeAllChilds=function(){for(var a=0;a<this._children.length;a++)this._children[a].removeAllChilds(),this._children[a].removeFromParent()};
GUI.DisplayObject.prototype.removeFromParent=function(){GUI.assert(null!=this._parent,"DisplayObject has no parent");this._parent.removeChild(this)};GUI.DisplayObject.prototype.render=function(){for(var a=0;a<this._children.length;a++)this._children[a].isVisible()&&this._children[a].render();this._dirty=this._hasDirty=!1};
GUI.DisplayObject.prototype.invalidateRect=function(){if(null===this.parent)return null;var a=GUI.Display.getTLPosition(this),a=GUI.Display.getNormalizedPosition(a.x,a.y),a=new GUI.Rect({width:this._size.width,height:this._size.height},{x:a.x,y:a.y});GUI.Display.dirtyRectangles.push(a);return a};GUI.Sprite=function(){GUI.DisplayObject.call(this)};GUI.Sprite.prototype=new GUI.DisplayObject;GUI.Sprite.prototype.constructor=GUI.Sprite;
GUI.Sprite.prototype.fromPath=function(a){var b=this;this.isVisible(!1);this.image=new Image;this.image.onload=function(a){b.remoteLoadHandler(a)};this.image.src=a};GUI.Sprite.prototype.remoteLoadHandler=function(){this.isVisible(!0);this.isDirty(!0);this.size(this.image.width,this.image.height)};GUI.Sprite.prototype.render=function(){var a=GUI.Display.getTLPosition(this);this._ctx.drawImage(this.image,a.x,a.y);this._dirty=!1;GUI.DisplayObject.prototype.render.call(this)};
GUI.Window=function(){GUI.DisplayObject.call(this);this._dirty=!1;this._backgroundColor="#000000"};GUI.Window.prototype=new GUI.DisplayObject;GUI.Window.prototype.constructor=GUI.Window;GUI.Window.prototype.backgroundColor=function(a){if("string"==typeof a)this._backgroundColor=a;return this._background};GUI.Window.prototype.render=function(){var a=GUI.Display.getTLPosition(this);this._ctx.fillStyle=this._backgroundColor;this._ctx.fillRect(a.x,a.y,this._size.width,this._size.height);GUI.DisplayObject.prototype.render.call(this)};
GUI.Mouse=function(){this._cursor=this._evt=null;this._movement="absolute";this._position={};this._position.x=0;this._position.y=0;this.createDisplayObject()};GUI.Mouse.prototype.createDisplayObject=function(){this._cursor=new GUI.Sprite;this._cursor.fromPath("ui/cursor.png");this._cursor.anchorPoint(0,1);this._cursor.tag("mouse")};
GUI.Mouse.prototype.getNormalizedPosition=function(){if(null==this._evt)return!1;var a=GUI.Display.Manager._stage.size();return{x:100/a.width*this._position.x/100,y:100/a.height*this._position.y/-100+1}};GUI.Mouse.prototype.position=function(a,b){if("number"===typeof a)this._position={x:a,y:b};return this._position};GUI.Mouse.prototype.injectMoveEvent=function(a){this._evt=a;this._updatePosition()};
GUI.Mouse.prototype._updatePosition=function(){if("absolute"===this._movement)this._position={x:this._evt.clientX,y:this._evt.clientY};else{var a=this.getMovement(),b=GUI.Display.Manager._stage.size();this._position.x+=a.x;this._position.y+=a.y;if(0>this._position.x)this._position.x=0;if(0>this._position.y)this._position.y=0;if(this._position.x>b.width)this._position.x=b.width;if(this._position.y>b.height)this._position.y=b.height}};GUI.Mouse.prototype.setRelative=function(){this._movement="relative"};
GUI.Mouse.prototype.setAbsolute=function(){this._movement="absolute"};GUI.Mouse.prototype.getMovement=function(){return this._evt.movementX?{x:this._evt.movementX,y:this._evt.movementY}:this._evt.webkitMovementX?{x:this._evt.webkitMovementX,y:this._evt.webkitMovementY}:this._evt.mozMovementX?{x:this._evt.mozMovementX,y:this._evt.mozMovementY}:{x:0,y:0}};
GUI.TextLabel=function(){GUI.DisplayObject.call(this);this._lineHeight=14;this._fontSize=12;this._font="Arial";this._text=this._fontStyle="";this._color="#000000"};GUI.TextLabel.prototype=new GUI.DisplayObject;GUI.TextLabel.prototype.constructor=GUI.TextLabel;
GUI.TextLabel.prototype.fontSize=function(a){if("number"==typeof a)this._fontSize=a,GUI.Display.Manager._ctx.font=this._fontSize+"px "+this._font,a=GUI.Display.Manager._ctx.measureText(this._text),this.size(a.width,a.height),this.invalidateRect();return this._fontSize};GUI.TextLabel.prototype.text=function(a){if("string"===typeof a)this._text=a,a=GUI.Display.Manager._ctx.measureText(this._text),this.size(a.width,a.height),this.invalidateRect();return this._text};
GUI.TextLabel.prototype.render=function(){var a=GUI.Display.getTLPosition(this);this._ctx.fillStyle=this._color;GUI.Display.Manager._ctx.font=this._fontSize+"px "+this._font;this._ctx.fillText(this._text,a.x,a.y+this._lineHeight);GUI.DisplayObject.prototype.render.call(this)};GUI.TextInput=function(){GUI.TextLabel.call(this);this._backgroundColor="rgba(255, 255, 255, 0.7)";this._caretColor="#000000";this._caretIndex=0;this._clearOnEnter=!0;this._enterCallback=null};GUI.TextInput.prototype=new GUI.TextLabel;
GUI.TextInput.prototype.constructor=GUI.TextInput;
GUI.TextInput.prototype.handleKeyDown=function(a){if(a.metaKey||a.ctrlKey||a.altKey)return null;switch(a.which){case 8:this._text=this._text.substr(0,this._caretIndex-1)+this._text.substr(this._caretIndex);0<this._caretIndex-1&&this._caretIndex--;break;case 13:"function"==typeof this._enterCallback&&this._enterCallback(this._text);if(this._clearOnEnter)this._text="",this._caretIndex=0;break;case 37:0<this._caretIndex-1&&this._caretIndex--;break;case 39:this._caretIndex<this._text.length&&this._caretIndex++;
break;default:var b=String.fromCharCode(a.which),b=a.shiftKey?b:b.toLowerCase();this._text=this._text.substr(0,this._caretIndex)+b+this._text.substr(this._caretIndex);this._caretIndex++}this._dirty=!0;this.invalidateRect()};
GUI.TextInput.prototype.render=function(){if(!this._dirty)return!1;var a=GUI.Display.getTLPosition(this);this._ctx.fillStyle=this._backgroundColor;this._ctx.fillRect(a.x,a.y,this._size.width,this._size.height);GUI.Display.Manager._ctx.font=this._fontSize+"px "+this._font;var b=a.x+this._ctx.measureText(this._text.substr(0,this._caretIndex)).width;this._ctx.strokeStyle=this._caretColor;this._ctx.beginPath();this._ctx.lineWidth=1;this._ctx.moveTo(b,a.y+this._lineHeight-this._fontSize);this._ctx.lineTo(b,
a.y+this._lineHeight);this._ctx.stroke();this._ctx.closePath();GUI.TextLabel.prototype.render.call(this)};GUI.TextArea=function(){GUI.TextLabel.call(this);this._backgroundColor="rgba(0, 0, 0, 0.5)";this._text="";this._breakOn="\n";this._padding=5;this._dirty=!0};GUI.TextArea.prototype=new GUI.DisplayObject;GUI.TextArea.prototype.constructor=GUI.TextArea;GUI.TextArea.prototype.text=function(a){if("string"===typeof a)this._text=a,this._dirty=!0,this.invalidateRect();return this._text};
GUI.TextArea.prototype.color=function(a){if("string"===typeof a)this._color=a,this._dirty=!0,this.invalidateRect();return this._color};
GUI.TextArea.prototype.render=function(){if(!this._dirty)return null;var a=GUI.Display.getTLPosition(this);this._ctx.fillStyle=this._backgroundColor;this._ctx.fillRect(a.x,a.y,this._size.width,this._size.height);this._ctx.fillStyle=this._color;for(var b=this._text.split(this._breakOn),c=1,d=0;d<b.length;d++){for(var e=b[d].split(" "),f=1;0<e.length&&f<=e.length;)this._ctx.measureText(e.slice(0,f).join(" ")).width>this._size.width?(1==f&&(f=2),this._ctx.fillText(e.slice(0,f-1).join(" "),a.x,a.y+this._lineHeight*
c),c++,e=e.splice(f-1),f=1):f++;0<f&&this._ctx.fillText(e.join(" "),a.x,a.y+this._lineHeight*c);c++}GUI.DisplayObject.prototype.render.call(this);this._dirty=!1};GUI.Display={};GUI.Display.dirtyRectangles=[];GUI.Display.Manager=new GUI.Manager;GUI.Display.getNormalizedPosition=function(a,b){return{x:100/window.innerWidth*a/100,y:100/window.innerHeight*b/-100+1}};GUI.Display.getDenormalizedPosition=function(a,b){var c=window.innerHeight;return{x:window.innerWidth*a,y:-1*c*b+c}};
GUI.Display.getTLPosition=function(a){a._parent&&GUI.Display.getTLPosition(a._parent);var b=GUI.Display.getDenormalizedPosition(a._position.x,a._position.y);return{x:b.x-a._size.width*a._anchorPoint.x,y:b.y-a._size.height*-(a._anchorPoint.y-1)}};GUI.Display.getObjectAtPoint=function(){console.log()};GUI.AssertException=function(a){this.message=a};GUI.AssertException.prototype.toString=function(){return"AssertException: "+this.message};
GUI.assert=function(a,b){if(!a)throw new GUI.AssertException(b);};
